Add `PF_HEATMAP` parameter (#202)
* Add PF_HEATMAP parameter

* Update planefence.conf

* Update planefence.sh

* Update planefence.config

* Update planefence

* Fix typo

diff --git a/rootfs/etc/s6-overlay/scripts/planefence b/rootfs/etc/s6-overlay/scripts/planefence
--- a/rootfs/etc/s6-overlay/scripts/planefence
+++ b/rootfs/etc/s6-overlay/scripts/planefence
@@ -1,13 +1,8 @@
 #!/command/with-contenv bash
 #shellcheck shell=bash
 
-# redirect stderr to stdout so it's picked up in the docker logs
-exec 2>&1
-# all errors will show a line number and the command used to produce the error
-SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd)/$(basename "$0")"
-trap 'echo -e "[ERROR] $SCRIPT_PATH in line $LINENO when executing: $BASH_COMMAND"' ERR
+source /scripts/common
 
-APPNAME="$(hostname)/planefence"
 LOOPTIME=$(sed -n 's/\(^\s*PF_INTERVAL=\)\(.*\)/\2/p' /usr/share/planefence/persist/planefence.config)
 [[ "$LOOPTIME" == "" ]] && LOOPTIME=60
 PLANEFENCEDIR=/usr/share/planefence
@@ -55,11 +50,11 @@ do
               [[ "$TIMING" != "" ]] && export BASETIME=$(date +%s.%2N) || unset BASETIME
               $PLANEFENCEDIR/planefence.sh
               endtime=$(date +%s)
-              [[ "$LOGLEVEL" != "ERROR" ]] && echo "[$APPNAME][$(date)] PlaneFence ran for $((endtime - starttime)) secs and will be running again at $(date -d @$(( $starttime + $LOOPTIME )) +"%Y/%m/%d %H:%M:%S")." || true
+              [[ "$LOGLEVEL" != "ERROR" ]] && "${s6wrap[@]}" echo "PlaneFence ran for $((endtime - starttime)) secs and will be running again at $(date -d @$(( $starttime + $LOOPTIME )) +"%Y/%m/%d %H:%M:%S")." || true
         else
-              echo "[$APPNAME][$(date)] /run/socket30003/dump1090-*-(date +%y%m%d).txt not found."
-              echo "[$APPNAME][$(date)] If this continues to happen after 5-10 minutes, check this:"
-              echo "[$APPNAME][$(date)] Is \"socket30003\" running? Is your feeder producing data?"
+              "${s6wrap[@]}" echo "/run/socket30003/dump1090-*-(date +%y%m%d).txt not found."
+              "${s6wrap[@]}" echo "If this continues to happen after 5-10 minutes, check this:"
+              "${s6wrap[@]}" echo "Is \"socket30003\" running? Is your feeder producing data?"
     fi
 	# [ -z "$TESTTIME" ] && LOOPTIME="$TESTTIME" # debug code
     wait
