final final nightly update

diff --git a/rootfs/etc/s6-overlay/scripts/screenshot b/rootfs/etc/s6-overlay/scripts/screenshot
--- a/rootfs/etc/s6-overlay/scripts/screenshot
+++ b/rootfs/etc/s6-overlay/scripts/screenshot
@@ -42,7 +42,7 @@ do
   starttime=$(date +%s)
   $PLANEFENCEDIR/pf-screenshot.sh
   endtime=$(date +%s)
-  [[ "$LOGLEVEL" != "ERROR" ]] && log_print INFO "Screenshot ran for $((endtime - starttime)) secs and will be running again at $(date -d @$(( starttime + LOOPTIME )) )." || true
+  # [[ "$LOGLEVEL" != "ERROR" ]] && log_print INFO "Screenshot ran for $((endtime - starttime)) secs and will be running again at $(date -d @$(( starttime + LOOPTIME )) )." || true
   if (( starttime + LOOPTIME > endtime )); then
       sleep $(( (starttime + LOOPTIME) - endtime )) &
   fi
