Rel5.3 (#40)
* Rel5.0-official (#30)

* added location fudging for the map

* build command update

* location fudging for maps

* location fudging for maps

* fixes for non-mile units

* backout planefence.py changes

* make ~/.planefence rwx upon creation

* improvements for obtaining a tail or flight number from socket30003

* minor change to rebase prep-planefence

* minor typo fix

* reduce logging

* airlinename remote lookup as a last resort

* latest

* foutje bedankt

* reducing remote lookup hits

* remote cache lookup hits reduction

* improvement to IGNORE DUPES to handle spaces in flight number field

* another INGOREDUPES fix

* cache bug fixed

* cache bug fixed

* minor issue fixed

* remote cache optimization

* added remote db check

* caching fix

* caching fix

* exception for name lookup for HMED flight numbers (tnx @sportsbadger)

* addtl exception work

* airline names parsing cleanup

* typo fix

* bug fix

* added built to hello string

* fixed HMED cache issue

* pre-release cleanup

* pre-release cleanup

* release 5.1

* bug fix to prevent local cache dupes

* bug fix to prevent local cache dupes

* bug fix to prevent local cache dupes

* retrieve airlinescodes from repo during cleanup runs

* retrieve airlinescodes from repo during cleanup runs - update

* Add icao 2 tail from cached mictronics database

* Update planefence.conf

* Add icao 2 tail from cached mictronics database

* Add zip package for icao 2 tail from cached mictronics database

* fixing stupid bug

* bug file in mictronic db lookup

* pf.sh lines 604+608: potential fix for dupes issue
pf.sh line 598: "read -ra" -> "read -r"
pt.sh line 136 added extra check for previous tweet

* improved logging

* major rewrite of record merging code, logging improvements

* README updates

* build script updates

* don't print more than 5 decimals in LAT/LON on Planefence website

* plane-alert custom fields-initial implementation

* added custom field tweeting to plane-alert

* fixed bug

* major plane-alert bug fix

* sorting fix

* initial implementation of plane-alert range
https://github.com/kx1t/docker-planefence/issues/39

* add PF_PARANGE to default config file

https://github.com/kx1t/docker-planefence/issues/39

* restrict planetweet tweets to 280 chars (257+url)

* implement link to ignore-list in planefence
https://github.com/kx1t/docker-planefence/issues/36

* changed planefence logging

* logging change

* added background image for PF and PA

* fixed background stretching

* added default background to build

* dockerfile bug fix

* typos

* Update version number

diff --git a/planefence/services.d/start_cleanup b/planefence/services.d/start_cleanup
--- a/planefence/services.d/start_cleanup
+++ b/planefence/services.d/start_cleanup
@@ -1,7 +1,7 @@
 #!/usr/bin/with-contenv bash
 #shellcheck shell=bash
 
-APPNAME="cleanup"
+APPNAME="$(hostname)/cleanup"
 
 echo "[$APPNAME][$(date)] Cleanup started as an s6 service"
 
@@ -64,10 +64,62 @@ CLEANUP ()
       tail -n $MAXLOGLINES /tmp/tweets.log >/tmp/tweets.log.tmp 2>/dev/null
       mv -f /tmp/tweets.log.tmp /tmp/tweets.log 2>/dev/null
     fi
+
+    # remove empty lines from ignore file
     sed -i '/^$/d' /usr/share/planefence/persist/planefence-ignore.txt 2>/dev/null
+
+    # pull new version of airlinenames
+    echo "###,pulled from github kx1t/planefence-airlinecodes at $(date),," >/tmp/airlinecodes.txt
+    if curl -s -L -f https://raw.githubusercontent.com/kx1t/planefence-airlinecodes/main/airlinecodes.txt >>/tmp/airlinecodes.txt && [[ "$(cat /tmp/airlinecodes.txt | wc -l)" -gt "100" ]]
+    then
+	mv -f /tmp/airlinecodes.txt /usr/share/planefence/persist
+    fi
+
+
   else
     echo "[$APPNAME][$(date)] $LOOPTIME set to 0 - cleanup skipped"
   fi
+}
+
+# GET_ICAO_DB: Mictronics updates their ICAO-to-Tail database once a week.
+# If the existing file is older than last Monday's (or if none exists), then get a new one
+GET_ICAO_DB()
+{
+    if (( $(date -r /run/planefence/icao2plane.txt +%s 2>/dev/null || echo 0) < $(date -d "next monday - 7 days" +%s) ))
+    then
+        printf "[$APPNAME][$(date)] Retrieving ICAO to TAIL database from https://www.mictronics.de ... "
+        # note - the curl won't fail, even if the file is not found because the PHP page doesn't return a 400 code but a regular result webpage
+        curl -s -L -f -o /tmp/icao24plus.zip https://www.mictronics.de/aircraft-database/icao24plus.php
+        if [[ "$?" != "0" ]]
+        then
+            echo "Failed!"
+            return 1
+        fi
+
+        printf "unzipping ... "
+        # unzipping *will* fail when the retrieved file is not a valid ZIP file
+        unzip -qq -d /tmp -o /tmp/icao24plus.zip 2>/dev/null
+        if [[ "$?" != "0" ]]
+        then
+            echo "Failed!"
+            return 1
+        fi
+
+        rm -f /tmp/icao24plus.zip
+        # now convert the text based file into a CSV file
+        printf "converting ... "
+        sed -i 's|\([0-9A-F]\{6\}\)\s*\([A-Z0-9\-]*\)\s*\([A-Z0-9]*\)\s*\(.*\)|\1,\2,\3,\4|g' /tmp/icao24plus.txt
+        if [[ "$?" != "0" ]]
+        then
+            echo "Failed!"
+            return 1
+        fi
+
+        mv -f /tmp/icao24plus.txt /run/planefence/icao2plane.txt
+        printf "done!\n"
+    else
+        echo "[$APPNAME][$(date)] ICAO to TAIL database is up to date"
+    fi
 }
 #
 #Now loop forevah:
@@ -75,6 +127,7 @@ while true
 do
   echo "[$APPNAME][$(date)] Performing a cleanup run..."
   CLEANUP
+  GET_ICAO_DB
   echo "[$APPNAME][$(date)] Cleanup done. Sleeping for $LOOPTIME"
   sleep $LOOPTIME
 done
