minor log message improvements

diff --git a/planefence/services.d/start_socket30003 b/planefence/services.d/start_socket30003
--- a/planefence/services.d/start_socket30003
+++ b/planefence/services.d/start_socket30003
@@ -61,9 +61,13 @@ do
 	 else
 		 # if $PF_SOCK30003HOST is defined, then check if we can reach it. Execute socket30003 if we can reach it, complain if we can't
 		 # we do this inside this endless loop so it will show in the logs regularly
-		 [[ $(timeout --preserve-status 5 netcat -z -v $PF_SOCK30003HOST 30003 2>/dev/null && echo $?) ]] && \
-		  	echo "[$APPNAME][$(date)] $(/usr/share/socket30003/socket30003.pl)" || \
-	  	  echo "[$APPNAME][$(date)] We cannot reach $PF_SOCK30003HOST on port 30003. Fix your readsb or dump1090 install to ensure that this port is enabled!"
+		 if [[ $(timeout --preserve-status 5 netcat -z -v $PF_SOCK30003HOST 30003 2>/dev/null && echo $?) ]]
+		 then
+		  	echo "[$APPNAME][$(date)] $(/usr/share/socket30003/socket30003.pl)"
+		 else
+	  	  echo "[$APPNAME][$(date)] We cannot reach \"$PF_SOCK30003HOST\" on port 30003."
+				echo "[$APPNAME][$(date)] If this error keeps on repeating. ensure that readsb/dump1090[-fa]/tar1090 is running and producing SBS data on port 30003!"
+		 fi
 	 fi
 	 echo "[$APPNAME][$(date)] socket30003 has exited... restarting in $LOOPTIME"
 	 sleep $LOOPTIME
