safety updates

diff --git a/planefence/services.d/start_planefence b/planefence/services.d/start_planefence
--- a/planefence/services.d/start_planefence
+++ b/planefence/services.d/start_planefence
@@ -35,6 +35,23 @@ PLANEFENCEDIR=/usr/share/planefence
 # Make sure the /run directory exists
 mkdir -p /run/planefence
 # -----------------------------------------------------------------------------------
+# Do one last check. If FEEDER_LAT= empty or 90.12345, then the user obviously hasn't touched the config file.
+if [[ "x$FEEDER_LAT" == "x" ]] || [[ "$FEEDER_LAT" == "90.12345" ]]
+then
+		sleep 10s
+		echo "----------------------------------------------------------"
+		echo "!!! STOP !!!! You haven't configured PlaneFence !!!!"
+		echo "Planefence will not run unless you edit it configuration."
+		echo "You can do this by pressing CTRL-c now and typing:"
+		echo "sudo nano -l ~/.planefence/planefence.config"
+		echo "Once done, restart the container and this message should disappear."
+		echo "----------------------------------------------------------"
+		while true
+		do
+				sleep 99999
+		done
+fi
+
 #
 # Set logging in planefence.conf:
 #
@@ -51,8 +68,8 @@ sed -i 's|\(^\s*LOGFILE=\).*|\1'"$LOGFILE"'|' /usr/share/planefence/planefence.c
 # -----------------------------------------------------------------------------------
 #
 # read the environment variables and put them in the planefence.conf file:
-[[ "x$FEEDER_LAT" != "x" ]] && sed -i 's/\(^\s*LAT=\).*/\1'"\"$FEEDER_LAT\""'/' /usr/share/planefence/planefence.conf || { echo "Error - \$FEEDER_LAT ($FEEDER_LAT) not defined"; exit 99; }
-[[ "x$FEEDER_LONG" != "x" ]] && sed -i 's/\(^\s*LON=\).*/\1'"\"$FEEDER_LONG\""'/' /usr/share/planefence/planefence.conf || { echo "Error - \$FEEDER_LONG not defined"; exit 99; }
+[[ "x$FEEDER_LAT" != "x" ]] && sed -i 's/\(^\s*LAT=\).*/\1'"\"$FEEDER_LAT\""'/' /usr/share/planefence/planefence.conf || { echo "Error - \$FEEDER_LAT ($FEEDER_LAT) not defined"; while :; do sleep 2073600; done; }
+[[ "x$FEEDER_LONG" != "x" ]] && sed -i 's/\(^\s*LON=\).*/\1'"\"$FEEDER_LONG\""'/' /usr/share/planefence/planefence.conf || { echo "Error - \$FEEDER_LONG not defined"; while :; do sleep 2073600; done; }
 [[ "x$PF_MAXALT" != "x" ]] && sed -i 's/\(^\s*MAXALT=\).*/\1'"\"$PF_MAXALT\""'/' /usr/share/planefence/planefence.conf
 [[ "x$PF_MAXDIST" != "x" ]] && sed -i 's/\(^\s*DIST=\).*/\1'"\"$PF_MAXDIST\""'/' /usr/share/planefence/planefence.conf
 [[ "x$PF_NAME" != "x" ]] && sed -i 's/\(^\s*MY=\).*/\1'"\"$PF_NAME\""'/' /usr/share/planefence/planefence.conf
@@ -174,22 +191,6 @@ cp -f /usr/share/planefence/stage/sort-table.js /usr/share/planefence/html/plane
 # directory - no recursion - just in case some idiot maps the persist directory to the host's "/"
 chmod a+rw /usr/share/planefence/persist /usr/share/planefence/persist/{.[!.]*,*}
 #
-# Do one last check. If FEEDER_LAT=90.12345, then the user obviously hasn't touched the config file.
-if [[ "$FEEDER_LAT"="90.12345" ]]
-then
-		sleep 10s
-		echo "----------------------------------------------------------"
-		echo "!!! STOP !!!! You haven't configured PlaneFence !!!!"
-		echo "Planefence will not run unless you edit it configuration."
-		echo "You can do this by pressing CTRL-c now and typing:"
-		echo "sudo nano -l ~/.planefence/planefence.config"
-		echo "Once done, restart the container and this message should disappear."
-		echo "----------------------------------------------------------"
-		while true
-		do
-				sleep 99999
-		done
-fi
 #--------------------------------------------------------------------------------
 # Now loop forever, after waiting for 1 cycle. The wait is so socket30003 can actually collect some data before we try to call PlaneFence
 #
